<html>
<head>
    <title>Report | Download | PDF</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        body {
            font-family: 'kalpurush', sans-serif;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        table, td, th {
            border: 1px solid black;
        }

        th, td {
            padding: 4px;
            font-family: 'kalpurush', sans-serif;
            font-size: 14px;
        }

        @page {
            header: page-header;
            footer: page-footer;
            background-image: url({{ public_path('images/cvcs_background.png') }});
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center center;
        }
    </style>
</head>
<body>
<h2 align="center">
    <img src="{{ public_path('images/custom2.png') }}" style="height: 80px; width: auto;"><br/>
    কাস্টমস এন্ড ভ্যাট কো অপারেটিভ সোসাইটি (সিভিসিএস) লিমিটেড
    <br/> নিবন্ধন নং - ০০০৩১
</h2>
<p align="center" style="padding-top: -20px;">
    <span style="font-size: 20px;">সদস্য অনুমোদন লগ রিপোর্ট <br/> </span><br/>
</p>


<div class="" style="padding-top: 0px;">
    <b>{{$member->name}} ({{$member->member_id}})</b> - {{date('Y')}}
    <table class="">
        <thead>
        <tr>
            <td colspan="6" style="background: rgba(192,192,192, 0.7);">অ্যাডমিন কার্যক্রম</td>
        </tr>
        <tr>
            <th style="background: rgba(124,252,0, 0.5);">#</th>
            <th style="background: rgba(124,252,0, 0.5);">মেম্বার</th>
            <th style="background: rgba(124,252,0, 0.5);">কার্যক্রম ধরণ</th>
            <th style="background: rgba(124,252,0, 0.5);">বর্ণনা</th>
            <th style="background: rgba(124,252,0, 0.5);">সময়কাল</th>
        </tr>
        </thead>
        <tbody>
        @php
            $counter = 1;

        @endphp
        @foreach($activitylogs as $activitylog)
            @php
                $admin = \App\User::findOrFail($activitylog->causer_id);
                $payment = null;
                $logDetail = $activitylog->description;
                if ($activitylog->log_name == 'approve_single_payment'){
                    $properties = $activitylog->properties->toArray();
                    $payment = \App\Payment::find($properties['payment_id']);
                    if($payment){
                       $logDetail = "সিঙ্গেল পেমেন্ট অনুমোদন ({$payment->payment_key}) \nপরিমান: {$payment->amount} [{$payment->bank} ({$payment->branch})]";
                    }

                } elseif($activitylog->log_name == 'bulk_payment_individual'){
                    $properties = $activitylog->properties->toArray();
                    $payment = \App\Payment::find($properties['payment_id']);
                    if($payment){
                       $logDetail = "বাল্ক পেমেন্ট অনুমোদন ({$payment->payment_key})\nজমাদানকারীঃ {$payment->payee->name}({$payment->payee->member_id}) \nপরিমান: {$payment->amount} [ব্যাংক: {$payment->bank} ({$payment->branch})]";
                    }

                }
            @endphp
            <tr>
                <td align="center">{{ bangla($counter++) }}</td>
                <td>{{ $admin->name}} <span>(<b>{{$admin->member_id}}</b>)</span></td>
                <td>{{$activitylog->description}}</td>
                <td>{{$logDetail}}</td>
                <td>{{$activitylog->created_at->format('F d, Y H:m')}}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>


<htmlpagefooter name="page-footer">
    <small>ডাউনলোডের সময়কালঃ <span style="font-family: Calibri;">{{ date('F d, Y, h:i A') }}</span></small><br/>
    <small style="font-family: Calibri; color: #6D6E6A;">Generated by: https://cvcsbd.com</small>
</htmlpagefooter>
</body>
</html>
