<html>
<head>
  <title>Report | Download | PDF</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <style>
  body {
    font-family: 'kalpurush', sans-serif;
  }

  table {
      border-collapse: collapse;
      width: 100%;
  }
  table, td, th {
      border: 1px solid black;
  }
  th, td{
    padding: 4px;
    font-family: 'kalpurush', sans-serif;
    font-size: 14px;
  }
  @page {
    header: page-header;
    footer: page-footer;
    background-image: url({{ public_path('images/cvcs_background.png') }});
    background-size: cover;              
    background-repeat: no-repeat;
    background-position: center center;
  }
  .graybackground {
    background: rgba(192,192,192, 0.7);
  }
  </style>
</head>
<body>
  <h2 align="center">
    <img src="{{ public_path('images/custom2.png') }}" style="height: 80px; width: auto;"><br/>
    কাস্টমস এন্ড ভ্যাট কো-অপারেটিভ সোসাইটি
  </h2>
  <p align="center" style="padding-top: -20px;">
    <span style="font-size: 20px;">সাধারণ রিপোর্ট</span><br/>
  </p>
  
  <div class="" style="padding-top: 0px;">
    <table class="">
      <tr>
        <td class="graybackground" width="60%">সর্বমোট সদস্য সংখ্যা</td>
        <td align="right">{{ bangla($registeredmembers) }} জন</td>
      </tr>
      <tr>
        <td class="graybackground">সর্বমোট সদস্যপদ বাবদ সফল পরিশোধ</td>
        <td  align="right">৳ {{ bangla($registeredmembers * 5000) }}</td>
      </tr>
      <tr>
        <td class="graybackground">সর্বমোট মাসিক কিস্তি বাবদ সফল পরিশোধ ({{ bangla(date('F, Y')) }} পর্যন্ত)</td>
        <td  align="right">৳ {{ bangla($totalapproved->totalamount - ($registeredmembers * 5000)) }}</td>
      </tr>
      <tr>
        <td class="graybackground">সর্বমোট মাসিক কিস্তি বাবদ বকেয়া ({{ bangla(date('F, Y')) }} পর্যন্ত)</td>
        <td  align="right">৳ {{ bangla($totalapproved->totalamount - ($registeredmembers * 5000)) }}</td>
      </tr>
    </table>
  </div>
 
  <htmlpagefooter name="page-footer">
    <small>ডাউনলোডের সময়কালঃ <span style="font-family: Calibri;">{{ date('F d, Y, h:i A') }}</span></small><br/>
    <small style="font-family: Calibri; color: #6D6E6A;">Generated by: https://cvcsbd.com</small>
  </htmlpagefooter>
</body>
</html>