<html>
<head>
  <title>Report | Download | PDF</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <style>
  body {
    font-family: 'kalpurush', sans-serif;
  }

  table {
      border-collapse: collapse;
      width: 100%;
  }
  table, td, th {
      border: 1px solid black;
  }
  th, td{
    padding: 4px;
    font-family: 'kalpurush', sans-serif;
    font-size: 13px;
  }
  @page {
    header: page-header;
    footer: page-footer;
    background-image: url({{ public_path('images/cvcs_background.png') }});
    background-size: cover;              
    background-repeat: no-repeat;
    background-position: center center;
  }
  .graybackground {
    background: rgba(192,192,192, 0.7);
  }
  </style>
</head>
<body>
  <h2 align="center">
    <img src="{{ public_path('images/custom2.png') }}" style="height: 80px; width: auto;"><br/>
    কাস্টমস এন্ড ভ্যাট কো-অপারেটিভ সোসাইটি
  </h2>
  <p align="center" style="padding-top: -20px;">
    <span style="font-size: 20px;">'{{ bangla(date('F d, Y', strtotime($startdate))) }}' হতে '{{ bangla(date('F d, Y', strtotime($enddate))) }}' পর্যন্ত আদায়কৃত অর্থের হিসাব</span><br/>
  </p>
  
  <div class="" style="padding-top: 0px;">
    <table class="">
      <tr class="graybackground">
        <th>#</th>
        <th width="60%">সদস্য</th>
        <th>ছবি</th>
        <th>সদস্য কর্তৃক মোট পরিশোধ</th>
      </tr>
      @php
        $counter = 1;
        $grandtotal = 0;
      @endphp
      @foreach($payments as $payment)
        @if($payment->user)
          <tr>
            <td align="center">১২১{{ bangla($counter) }}</td>
            <td>
              <b>{{ $payment->user->name_bangla }}</b>, {{ $payment->user->position->name }}<br/>
              আইডিঃ {{ $payment->user->member_id }}, ফোনঃ {{ $payment->user->mobile }}
            </td>
            <td align="center">
              {{-- @if($payment->user->image != null && file_exists(public_path('images/users/'.$payment->user->image)))
                 <img src="{{ public_path('images/users/'.$payment->user->image)}}" style="height: 50px; width: auto;" />
              @else
                <img src="{{ public_path('images/user.png')}}" style="height: 50px; width: auto;" />
              @endif --}}
            </td>
            <td align="center">৳ {{ bangla($payment->totalamount) }}</td>
          </tr>
          @php
            $counter++;
            $grandtotal = $grandtotal + $payment->totalamount
          @endphp
        @else
        <tr>
          <td></td>
          <td>ERROR: {{ $payment->member_id }}</td>
          <td></td>
          <td align="center">৳ {{ bangla($payment->totalamount) }}</td>
        </tr>
        @endif
      @endforeach

      <tr class="graybackground">
        <th></th>
        <th></th>
        <th align="right">মোট</th>
        <th>৳ {{ bangla($grandtotal) }}</th>
      </tr>
      
    </table>
  </div>
 
  <htmlpagefooter name="page-footer">
    <small>ডাউনলোডের সময়কালঃ <span style="font-family: Calibri;">{{ date('F d, Y, h:i A') }}</span></small><br/>
    <small style="font-family: Calibri; color: #6D6E6A;">Generated by: https://cvcsbd.com</small>
  </htmlpagefooter>
</body>
</html>